image: hipay/gitlab-ci-base:jessie

stages:
 - package

variables:
  GIT_DEPTH: 10

#########################
####  JOBS          ####
########################

package:
 stage: package
 before_script:
  - apt-get install -y zip sshpass
 script:
  - echo "Package module $CI_COMMIT_REF_SLUG"
  - ./package-ready-for-prestashop/builder/module_builder.sh -v $CI_COMMIT_REF_SLUG
  - chmod u+x bin/deployment/deploy_package.sh
  - ./bin/deployment/deploy_package.sh
 artifacts:
  paths:
    - ./package-ready-for-prestashop
 tags:
    - pi-commerce-no-overlay
